config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/team'
  #get 'home/heroes'
  post 'home/team' => 'home#team'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
before_action :common, :only => [:index, :team]





  def common
    
    @hero_name = Faker::Superhero.name
    @hero_power = Faker::Superhero.power
    @corp_job = Faker::Company.bs
    @corp_title = Faker::Job.title 
    @hero_descriptor = Faker::Superhero.descriptor
    @rand_num = rand(1...1000)

  #Randomly picking the avatar  
    @rand_set = rand(1..4)
    if @rand_set == 1
      @set_num = "set4"
    elsif @rand_set == 2
      @set_num = "set3"
    elsif @set_num == 3
      @set_num = "set2"
    else
      @set_num = "set1"
    end

#Randomly picking the background
    @bg_set = rand(1..4)
    if @bg_set == 1
      @bg_num = "bg1"
    elsif @bg_set == 2
      @bg_num = "bg2"
    elsif @bg_num == 3
      @bg_num = "bg3"
    else
      @bg_num = "bg4"
    end

    @hero_image = Faker::Avatar.image(@rand_num, "300x300", "png", @set_num, @bg_num)
  end

  def index
  end

  def team 
    @team_number = params[:team_number].to_i
  end
  
  def heroes
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_create.html.erb
  
    <div class="row">
    </br>
        <div class="col-md-4">
            <%= form_tag home_team_path,:method => "POST" do %>
            <%= select_tag(:team_number, options_for_select([
              ["1",1],
              ["2",2],
              ["3",3],
              ["4",4],
              ["5",5],
              ["6",6],
              ["7",7],
              ["8",8],
              ["9",9],
              ["10",10],
            ]), class: 'form-control') %></br></br>
             <%= submit_tag 'Build Your Team', class: "btn btn-primary"%>
            <% end %>
        </div>
         <div class="col-md-4">
           cvcvcv
        </div>
         <div class="col-md-4">

        </div>
    </div>
  

app/views/home/_navbar.html.erb
  
   <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Super Hero Name Generator', root_path, class: "navbar-brand bloo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home Page', root_path %></li>
        <li><%= link_to 'Create A Team', home_team_path %></li>
      <!-- <li><%= link_to 'Hero Page', home_team_path %></li> -->
       
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/_show.html.erb
<% @team_number.times do %>



<div class="row">
    <div class="col-md-4">
<%
 @rand_num = rand(1...1000)

  #Randomly picking the avatar  
    @rand_set = rand(1..4)
    if @rand_set == 1
      @set_num = "set4"
    elsif @rand_set == 2
      @set_num = "set3"
    elsif @set_num == 3
      @set_num = "set2"
    else
      @set_num = "set1"
    end

#Randomly picking the background
    @bg_set = rand(1..4)
    if @bg_set == 1
      @bg_num = "bg1"
    elsif @bg_set == 2
      @bg_num = "bg2"
    elsif @bg_num == 3
      @bg_num = "bg3"
    else
      @bg_num = "bg4"
    end

    @hero_image = Faker::Avatar.image(@rand_num, "300x300", "png", @set_num, @bg_num)
  


%>
      <img src="<%= @hero_image %>"> 
    </div>
       <div class="col-md-4">
          <h3>Super Hero Name</h3><h4><%= Faker::Superhero.name %></h4>
          <h3>Super Hero Power</h3><h4><%= Faker::Superhero.power %></h4></br></br></br>
          <h5>Employed as</h5><h6><%= Faker::Job.title %></h6>
          <h5>Employed by</h5><h6><%= Faker::Company.bs %></h6>
       </div>
        <div class="col-md-4">
          ....
        </div>
            <div class = 'row'>
                <div class="col-md-12">
                <hr>
                </div>
            </div>
    </div>
   <% end %> 

app/views/home/heroes.html.erb
<h1>Heroes Page</h1>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= link_to 'Click Here To Generate A New Superhero', root_path %></h3>
  </div>
  <div class="panel-body">
  hghghghg
     <%= @hero_name %>
    </div>
  
<div class="panel-footer">
   <%= link_to 'Create A Whole Superhero Team', home_team_path %></div>
</div>

app/views/home/index.html.erb
<h1 class="bigname">Super Duper Hero Generator</h1>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"></h3><%= link_to 'Click Here To Generate A New Superhero', root_path %>
  </div>
  <div class="panel-body">
  <div class="row">
    <div class="col-md-4">
      <img src="<%= @hero_image %>">
    </div>
       <div class="col-md-4">
          <h3>Super Hero Name</h3><h4><%= @hero_name.upcase %></h4>
          <h3>Super Hero Power</h3><h4><%= @hero_power %></h4></br></br></br>
          <h5>Employed as</h5><h6><%= @corp_title.upcase %></h6>
          <h5>Employed by</h5><h6><%= @corp_job.upcase %></h6>
       </div>
        <div class="col-md-4">
          ....
        </div>
        </div>
      </div>
    </div>
  
<div class="panel-footer">
   <%= link_to 'Create A Whole Superhero Team', home_team_path %></div>
</div>

app/views/home/team.html.erb
<h1>Create A Team</h1>

<% if @team_number > 0%>
You picked <%= @team_number %> team members
<% else %>
lets build a team
<% end %>


<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title gray">
    <% if @team_number > 0 %>
    'Your Super Hero Team Is'
    <% else %>
    'How Many Team Members Do You Want?'</h3>
    <% end %>
  </div>
  <div class="panel-body">
   <% if @team_number > 0%>
    <%= render 'home/show' %>
    <% else %>
    <%= render 'home/create' %>
   <% end %>
  </div>
  
<div class="panel-footer">
   <%= link_to 'Create A Whole Superhero Team', home_team_path %></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hero2</title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'home/navbar' %>

   <div class = "container">
    <%= yield %>
   </div>
    </br></br></br></br>
    <center>
    Copyright © CARLOS BOYKINS - All Rights Reserved
    </center>
  </body>
  
</html>